# 站点名称
site_name: "ilolicon"

# 表单字段定义
form_fields:
  category: "type" # 类别字段（固定发布到种子区）
  source: "source_sel[4]" # 地区字段
  medium: "medium_sel[4]" # 媒介字段
  video_codec: "codec_sel[4]" # 视频编码字段
  audio_codec: "audiocodec_sel[4]" # 音频编码字段
  resolution: "standard_sel[4]" # 分辨率字段
  team: "team_sel[4]" # 制作组字段
  tags[4][]: "tags[]" # 标签字段

source_parsers:
  source_params:
    type:
      source_key: "类型"
    source:
      source_key: "地区"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"

  standard_keys:
    type:
      "动漫": "category.animation"
      "动画": "category.animation"
      "Animation": "category.animation"
      "Anime": "category.animation"

    source:
      "日本 (JPN)": "source.japan"
      "大陆 (CHN)": "source.china"
      "欧美 (West)": "source.western"
      "台湾 (TWN)": "source.taiwan"
      "韩国 (KOR)": "source.korea"
      "香港 (HKG)": "source.hongkong"
      "印度 (IND)": "source.india"
      "俄国 (RUS)": "source.russia"
      "泰国 (THA)": "source.thailand"
      "其它 (Other)": "source.other"

    medium:
      "UHD Blu-ray": "medium.uhd_bluray"
      "Blu-ray": "medium.bluray"
      "Remux": "medium.remux"
      "Encode": "medium.encode"
      "HDTV": "medium.hdtv"
      "WEB-DL": "medium.webdl"
      "DVD": "medium.dvd"
      "CD": "medium.cd"
      "Other": "medium.other"

    video_codec:
      "AVC/x264": "video.h264"
      "HEVC/x265": "video.h265"
      "AV1": "video.av1"
      "VC-1": "video.vc1"
      "MPEG-2": "video.mpeg2"
      "Other": "video.other"

    audio_codec:
      "AAC": "audio.aac"
      "AC3/DD": "audio.ac3"
      "DDP/E-AC3": "audio.ddp"
      "MP3": "audio.mp3"
      "FLAC": "audio.flac"
      "DTS": "audio.dts"
      "TrueHD": "audio.truehd"
      "LPCM": "audio.lpcm"
      "DTS-HD MA": "audio.dts_hd_ma"
      "DTS:X": "audio.dtsx"
      "OPUS": "audio.opus"
      "Other": "audio.other"

    resolution:
      "2160p/4K": "resolution.r2160p"
      "1080p": "resolution.r1080p"
      "1080i": "resolution.r1080i"
      "720p": "resolution.r720p"
      "SD": "resolution.sd"
      "Other": "resolution.other"

    team:
      "VCB-Studio": "team.vcb-studio"
      "7³ACG": "team.7acg"
      "AI-Raws": "team.ai-raws"
      "ANK-Raws": "team.ank-raws"
      "LittleBakas!": "team.littlebakas"
      "mawen1250": "team.mawen1250"
      "jsum@U2": "team.jsum"
      "Moozzi2": "team.moozzi2"
      "Snow-Raws": "team.snow-raws"
      "CMCT": "team.cmct"
      "GodDramas": "team.goddramas"
      "beAst": "team.beast"
      "Other": "team.other"

mappings:
  # 固定发布到“种子区”（不选特别区）
  type:
    "category.animation": "405"
    "default": "405"

  source:
    "source.japan": "6"
    "source.china": "1"
    "source.western": "4"
    "source.taiwan": "3"
    "source.korea": "5"
    "source.hongkong": "2"
    "source.india": "7"
    "source.russia": "8"
    "source.thailand": "11"
    "source.other": "13"
    "default": "13"

  medium:
    "medium.uhd_bluray": "14"
    "medium.bluray": "1"
    "medium.remux": "3"
    "medium.encode": "7"
    "medium.hdtv": "5"
    "medium.webdl": "12"
    "medium.dvd": "2"
    "medium.cd": "8"
    "medium.other": "11"
    "default": "11"

  video_codec:
    "video.h264": "9"
    "video.h265": "8"
    "video.av1": "15"
    "video.vc1": "12"
    "video.mpeg2": "13"
    "video.other": "5"
    "default": "5"

  audio_codec:
    "audio.aac": "6"
    "audio.ac3": "13"
    "audio.ddp": "20"
    "audio.mp3": "21"
    "audio.flac": "1"
    "audio.dts": "3"
    "audio.truehd": "9"
    "audio.lpcm": "15"
    "audio.dts_hd_ma": "10"
    "audio.dtsx": "23"
    "audio.opus": "24"
    "audio.other": "14"
    "default": "14"

  resolution:
    "resolution.r2160p": "5"
    "resolution.r1080p": "1"
    "resolution.r1080i": "2"
    "resolution.r720p": "3"
    "resolution.sd": "4"
    "resolution.other": "9"
    "default": "9"

  team:
    "team.vcb-studio": "11"
    "team.7acg": "15"
    "team.ai-raws": "42"
    "team.ank-raws": "48"
    "team.littlebakas": "49"
    "team.mawen1250": "50"
    "team.jsum": "40"
    "team.moozzi2": "53"
    "team.snow-raws": "39"
    "team.cmct": "46"
    "team.goddramas": "41"
    "team.beast": "47"
    "team.other": "5"
    "default": "5"

  tag:
    "tag.国语": 5
    "tag.粤语": 23
    "tag.中字": 6
    "tag.英字": 18 # 对应 ENSub
    "tag.特效": 22
    "tag.DIY": 4
    "tag.杜比": 13 # 对应 DoVi
    "tag.HDR": 7
    "tag.HDR10+": 14
    "tag.Atmos": 16
    "tag.原生": 9 # 对应 原生原盘
    "tag.LOLI": 11
    "tag.无对白": 24
    "tag.GalGame": 19
    "tag.分集": 21
    "tag.其他": 10
    "default": null # 默认不勾选任何标签
