# PTLover站点的配置文件
# 基于三层解耦模型重构，包含source_parsers和标准化的mappings

site_name: "PTLover"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
form_fields:
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"  # HTML表单中没有音频编码字段，但保留以兼容
  resolution: "standard_sel[4]"
  team: "team_sel[4]"
  source: "source_sel[4]"
  category: "type"  # 类别字段映射到type参数

# 标准化键映射 - 定义源文本到标准化键的映射规则
# source_parsers部分：定义如何从原始数据解析出标准化参数
source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"
    source:
      source_key: "产地"

  # 标准化键映射规则（从原始文本到标准化键）
  standard_keys:
    type:
      "综艺": "category.tv_shows"
      "HQ音频": "category.music"
      "其他": "category.other"
      "体育": "category.sports"
      "MV": "category.mv"
      "脱口秀": "category.tv_shows"
      "电视剧": "category.tv_series"
      "动画": "category.animation"
      "纪录片": "category.documentaries"
      "电影": "category.movie"
      "游戏": "category.game"
      "音频": "category.music"
      "直播秀": "category.live_show"
      "写真": "category.photography"
      "绘本": "category.illustration"
      "国产": "category.domestic"
      "步兵": "category.unedited"
      "骑兵": "category.edited"

    medium:
      "Track": "medium.track"
      "CD": "medium.cd"
      "DVDR": "medium.dvd"
      "HDTV": "medium.hdtv"
      "MiniBD": "medium.minibd"
      "Encode": "medium.encode"
      "Remux": "medium.remux"
      "HD DVD": "medium.hddvd"
      "Blu-ray": "medium.bluray"
      "WEB-DL(TV)": "medium.webdl"
      "BDMV": "medium.bdmv"

    video_codec:
      "H.264": "video.h264"
      "VC-1": "video.vc1"
      "Xvid": "video.xvid"
      "MPEG-2": "video.mpeg2"
      "Other": "video.other"
      "H.265(HEVC)": "video.h265"
      "AV1": "video.av1"
      "AVC": "video.h264"
      "MPEG-4": "video.mpeg4"
      "VP9": "video.vp9"

    resolution:
      "1080p": "resolution.r1080p"
      "1080i": "resolution.r1080i"
      "720p": "resolution.r720p"
      "SD": "resolution.sd"
      "2160P": "resolution.r2160p"
      "8K": "resolution.r4320p"
      "480P": "resolution.r480p"

    team:
      "TTG": "team.ttg"
      "sunny": "team.sunny"
      "HHWEB": "team.hhweb"
      "52pt": "team.pt52"
      "OpenCD": "team.opencd"
      "MrHulk": "team.mrhulk"
      "JPTVclub": "team.jptvclub"
      "DUSKLiGHT": "team.dusklight"
      "ADWeb": "team.adweb"
      "DBTV": "team.dbtv"
      "PTerWEB": "team.pterweb"
      "AilMWeb": "team.ailmweb"
      "HDH": "team.hdh"
      "NTb": "team.ntb"
      "Raws": "team.raws"
      "HDS": "team.hds"
      "ZWEX": "team.zwex"
      "FRDS": "team.frds"
      "HDHome": "team.hdhome"
      "QHstudIo": "team.qhstudio"
      "UBWEB": "team.ubweb"
      "WiKi": "team.wiki"
      "MySiLU": "team.mysilu"
      "CHD": "team.chd"
      "Other": "team.other"

    source:
      "大陆": "source.china"
      "香港": "source.hongkong"
      "台湾": "source.taiwan"
      "欧美": "source.western"
      "日本": "source.japan"
      "韩国": "source.korea"
      "印度": "source.india"
      "Other": "source.other"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数
mappings:
  type:
    "category.tv_shows": "414"
    "category.music": "408"
    "category.other": "409"
    "category.sports": "407"
    "category.mv": "406"
    "category.tv_series": "402"
    "category.animation": "405"
    "category.documentaries": "404"
    "category.movie": "401"
    "category.game": "418"
    "category.live_show": "411"
    "category.photography": "420"
    "category.illustration": "417"
    "category.domestic": "416"
    "category.unedited": "415"
    "category.edited": "410"
    "default": "409"

  medium:
    "medium.track": "9"
    "medium.cd": "8"
    "medium.dvd": "6"
    "medium.hdtv": "5"
    "medium.minibd": "4"
    "medium.encode": "7"
    "medium.remux": "3"
    "medium.hddvd": "2"
    "medium.bluray": "1"
    "medium.webdl": "10"
    "medium.bdmv": "11"
    "default": "0"

  video_codec:
    "video.h264": "1"
    "video.vc1": "2"
    "video.xvid": "3"
    "video.mpeg2": "4"
    "video.other": "5"
    "video.h265": "6"
    "video.av1": "7"
    "default": "5"

  resolution:
    "resolution.r1080p": "1"
    "resolution.r1080i": "2"
    "resolution.r720p": "3"
    "resolution.sd": "4"
    "resolution.r2160p": "5"
    "resolution.r4320p": "6"
    "resolution.r480p": "7"
    "default": "0"

  source:
    "source.china": "1"
    "source.hongkong": "2"
    "source.taiwan": "3"
    "source.western": "4"
    "source.japan": "5"
    "source.korea": "6"
    "source.india": "7"
    "source.other": "99"
    "default": "99"

  team:
    "team.ttg": "6"
    "team.sunny": "7"
    "team.hhweb": "8"
    "team.pt52": "14"
    "team.opencd": "26"
    "team.mrhulk": "25"
    "team.jptvclub": "24"
    "team.dusklight": "23"
    "team.adweb": "22"
    "team.dbtv": "21"
    "team.pterweb": "20"
    "team.ailmweb": "19"
    "team.hdh": "18"
    "team.ntb": "17"
    "team.raws": "16"
    "team.hds": "1"
    "team.zwex": "13"
    "team.frds": "12"
    "team.hdhome": "11"
    "team.qhstudio": "10"
    "team.ubweb": "9"
    "team.wiki": "4"
    "team.mysilu": "3"
    "team.chd": "2"
    "team.other": "5"
    "default": "5"

  tag:
    "tag.DIY": 4
    "tag.国语": 5
    "tag.中字": 6
    "tag.HDR": 7
    "default": null
